- name: Install Mosquitto
  apt:
    name: mosquitto
    state: present

- name: Install MQTT client
  apt:
    name: mosquitto-clients
    state: present

- name: Add configuration
  template:
    src: configuration.j2
    dest: /etc/mosquitto/conf.d/prisms.conf
  register: add_configuration

- name: Create passwd if it doesn't already exist
  file:
    state: touch
    path: /etc/mosquitto/passwd
  changed_when: False

- name: Check if username already exists
  shell: "grep {{ username }} /etc/mosquitto/passwd | wc -l"
  register: username_exists
  changed_when: False

- name: Add username and password
  command: "mosquitto_passwd -b /etc/mosquitto/passwd {{ username }} {{ password }}"
  when: "username_exists.stdout != '1'"
  register: add_username

- name: Start mosquitto
  service:
    name: mosquitto
    state: restarted
    enabled: yes
  when: add_configuration.changed or add_username.changed
